In [ ]:
import numpy as np

In [25]:
np_heights = np.array([[1.75, 1.65, 1.8, 1.5],[3.56, 1.46, 2.45, 4.43]])
print(np_heights)

[[1.75 1.65 1.8  1.5 ]
 [3.56 1.46 2.45 4.43]]


In [23]:
np.sort(np_heights[0])

array([1.5 , 1.65, 1.75, 1.8 ])

In [24]:
print(np.median(np_heights[:,0]))

2.6550000000000002


In [ ]:
print (np.__version__)

In [ ]:
np.info(np.eye)

In [ ]:
arr7 = np.array([9,5,2,67,3,5,2])
arr7[0::3] = 0
print(arr7)

In [ ]:
arr10 = np.array([9,5,2,67,3,5,2])
arr10[0:3] = 0
print(arr10)

In [ ]:
data = [2,3,5,3,4,5]
# array from list
arr = np.array(data)

print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr[arr < 4])

In [ ]:
arr5 = np.array([4,7,8,2,6,9,5,7])
arr5 < 5

In [ ]:
arr2 = np.array([1,2,3,5,7], dtype = np.float)
print(arr2)
print(arr2.dtype)
print(len(arr2))
print(arr2.size)
print(arr2.ndim)

In [ ]:
data1 = [4,5,1,8,3]
z = np.array(data1)
print(z)

In [ ]:
arr3 = np.arange(0,30,1.5)
arr3

In [ ]:
arr4 = np.linspace(0,5,30)
arr4

In [55]:
# creating multi-demensional array
matrix = np.array([(10,7,4),(3,2,1)])
print(matrix)

[[10  7  4]
 [ 3  2  1]]


In [58]:
a = np.median(matrix, axis = 1)

In [59]:
print(a)

[7. 2.]


In [ ]:
print(np.resize(matrix,(2,2)))

In [ ]:
print(matrix.shape)
# двумерный массив ndim = 2
print(matrix.ndim) 
print(matrix.size)

In [ ]:
print(matrix.reshape(1,6))
# one row and 6 columns

In [ ]:
new_matrix = np.arange(16).reshape(2,8)
print(new_matrix)

In [ ]:
np.delete(new_matrix, 0, axis = 1)