In [2]:
import numpy as np

In [4]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
z = np.zeros_like(x)
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [6]:
y = np.triu_indices_from(z)
y

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4], dtype=int64),
 array([0, 1, 2, 3, 4, 1, 2, 3, 4, 2, 3, 4, 3, 4, 4], dtype=int64))

In [9]:
x[y] = True
x

array([[ 1,  1,  1,  1,  1],
       [ 5,  1,  1,  1,  1],
       [10, 11,  1,  1,  1],
       [15, 16, 17,  1,  1],
       [20, 21, 22, 23,  1]])

In [10]:
x[y] = False
x

array([[ 0,  0,  0,  0,  0],
       [ 5,  0,  0,  0,  0],
       [10, 11,  0,  0,  0],
       [15, 16, 17,  0,  0],
       [20, 21, 22, 23,  0]])